# Generated by Django 6.0.6 on 2026-06-30 03:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('pt', 'Portuguese'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ru', 'Russian'), ('it', 'Italian'), ('tr', 'Turkish'), ('vi', 'Vietnamese'), ('id', 'Indonesian'), ('bn', 'Bengali'), ('ur', 'Urdu'), ('nl', 'Dutch'), ('pl', 'Polish'), ('th', 'Thai')], max_length=10)),
                ('file', models.FileField(help_text='WebVTT (.vtt) file.', upload_to='captions/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['vtt'])])),
                ('is_default', models.BooleanField(default=False, help_text='Show this language first in the captions menu.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='videos.video')),
            ],
            options={
                'ordering': ['-is_default', 'language'],
                'unique_together': {('video', 'language')},
            },
        ),
    ]
